kitchen/urls.py
from django.urls import path

from kitchen.views import (
    index,
    DishTypeListView,
    DishListView,
    CookListView,
    DishDetailView,
    CookDetailView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    delete_cook_from_dish,
    assign_cook_to_dish,
)

urlpatterns = [
    path("", index, name="index"),
    path("dishtype/", DishTypeListView.as_view(), name="dish-type-list"),
    path(
        "dishtype/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dishtype/update/<int:pk>/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dishtype/delete/<int:pk>/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("dish/", DishListView.as_view(), name="dish-list"),
    path("dish/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path(
        "dish/create/",
        DishCreateView.as_view(),
        name="dish-create",
    ),
    path(
        "dish/update/<int:pk>/",
        DishUpdateView.as_view(),
        name="dish-update",
    ),
    path(
        "dish/delete/<int:pk>/",
        DishDeleteView.as_view(),
        name="dish-delete",
    ),
    path("cook/", CookListView.as_view(), name="cook-list"),
    path("cook/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path(
        "cook/create/",
        CookCreateView.as_view(),
        name="cook-create",
    ),
    path(
        "cook/update/<int:pk>/",
        CookUpdateView.as_view(),
        name="cook-update",
    ),
    path("cook/delete/<int:pk>/", CookDeleteView.as_view(), name="cook-delete"),
    path(
        "cook/<int:pk>/assign_to_dish/",
        assign_cook_to_dish,
        name="cook-assign-to-dish",
    ),
    path(
        "cook/<int:pk>/delete_from_dish/",
        delete_cook_from_dish,
        name="cook-delete-from-dish",
    ),
]

app_name = "kitchen"

restaurant/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["first_name"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Dish(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        ordering = ["name"]
        verbose_name = "dish"
        verbose_name_plural = "dishes"

    def __str__(self) -> str:
        return self.name

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.form import (
    DishForm,
    CookCreateForm,
    CookYearExperienceUpdateForm,
    DishTypeSearchForm,
    CookSearchForm,
    DishSearchForm,
)
from kitchen.models import Cook, Dish, DishType


@login_required
def index(request):
    num_cooks = Cook.objects.count()
    num_dish_types = DishType.objects.count()
    num_dishes = Dish.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dish_types": num_dish_types,
        "num_dishes": num_dishes,
        "num_visits": num_visits,
    }

    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dishes_type_list"
    template_name = "kitchen/dishes_type_list.html"
    paginate_by = 5
    queryset = DishType.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypeSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(name__icontains=form.cleaned_data["name"])

        return self.queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    fields = "__all__"
    template_name = "kitchen/dishes_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    fields = "__all__"
    template_name = "kitchen/dishes_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("kitchen:dish-type-list")
    template_name = "kitchen/dishes_type_confirm_delete.html"


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    queryset = Dish.objects.select_related("dish_type")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(name__icontains=form.cleaned_data["name"])

        return self.queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")
    template_name = "kitchen/dish_confirm_delete.html"


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5
    queryset = Cook.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(initial={"username": username})

        return context

    def get_queryset(self):
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )

        return self.queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    context_object_name = "cooks"
    queryset = Cook.objects.prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookYearExperienceUpdateForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


@login_required
def assign_cook_to_dish(request, pk):
    dish = Dish.objects.get(pk=pk)
    dish.cooks.add(request.user.id)
    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))


@login_required
def delete_cook_from_dish(request, pk):
    dish = Dish.objects.get(pk=pk)
    dish.cooks.remove(request.user.id)
    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Restaurant Kitchen Service</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
{% load static %}
     <link rel="stylesheet" href="{% static 'css/styles.css' %}">
     <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>
      <div class="col-sm-9">
        {% block content %}
        {% endblock %}
        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.prev_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
    <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}

  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
     <a class="list-group-item list-group-item-action list-group-item-secondary" href="{% url "kitchen:cook-detail" pk=user.id %}">{{ user.username }} </a>
     <a class="list-group-item list-group-item-action list-group-item-secondary" href="{% url "logout" %}">Logout</a>
  {% else %}
  <a class="list-group-item list-group-item-action list-group-item-secondary" href="{% url "login" %}">Login</a>
  {% endif %}
  <a class="list-group-item list-group-item-action" href="{% url 'kitchen:index' %}">Home page</a>
  <a class="list-group-item list-group-item-action" href="{% url 'kitchen:dish-type-list' %}">Types of dishes</a>
  <a class="list-group-item list-group-item-action" href="{% url 'kitchen:dish-list' %}">Dishes</a>
  <a class="list-group-item list-group-item-action" href="{% url 'kitchen:cook-list' %}">Cooks</a>
</ul>

templates/kitchen/cook_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete cook?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-outline-danger">
  </form>
{% endblock %}

templates/kitchen/cook_detail.html
{% extends "base.html" %}

{% block content %}
      <h1>
    Username: {{ cooks.username }}

    <a href="{% url "kitchen:cook-delete" pk=cooks.id %}" class="btn btn-outline-danger" role="button">Delete</a>
  </h1>

    <p>
      <strong>Username: </strong>{{ cooks.username }}<br>
      <strong>Years of experience: </strong> {{ cooks.years_of_experience }}
    <strong>Years of experience:</strong> {{ cooks.years_of_experience }}
    <a href="{% url "kitchen:cook-update" pk=cooks.id %}" class="btn btn-outline-secondary" role="button">Edit years of experience</a>
    </p>

  {% if cooks.dishes.all %}
    <h2>Dishes:</h2>

    {% for dish in cooks.dishes.all %}
        <ul>
          <li class="list_item">
            <div class="item_content">
              <p>
                <strong>Types of dishes:</strong>
                {{ dish.dish_type.name }}<br>
                <strong>Name: </strong>
                <a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a>
              </p>
            </div>
          </li>
        </ul>
    {% endfor %}

  {% else %}
    <p>This cook does not have a dish</p>
  {% endif %}

{% endblock %}

templates/kitchen/cook_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-outline-secondary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Cooks
    <a href="{% url 'kitchen:cook-create' %}" class="btn btn-outline-secondary">
      Create
    </a>
  </h1>
  <br>
  <form action="" method="get" class="form-inline">
    {{search_form|crispy }}
      <input type="submit" class="btn btn-outline-secondary" value="🔎">
  </form>
  <br>
    <table class="table table table-dark">
      <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Last name</th>
        <th scope="col">Username</th>
        <th scope="col">Year of experience</th>
      </tr>
      </thead>
      <tbody>
      {% if cook_list %}
        {% for cook in cook_list %}
          <tr>
            <th scope="col">
           <a href="{% url 'kitchen:cook-detail' pk=cook.id %}">{{ cook.id }}</a>
            </th>
            <td>{{ cook.first_name }} </td>
            <td>{{ cook.last_name }} </td>
            <td scope="col">{{ cook.username }}</td>
            <td>{{ cook.years_of_experience }}</td>
          </tr>
        {% endfor %}
      {% else %}
        <th scope="col">There are not cooks</th>
      {% endif %}
      </tbody>
    </table>
{% endblock %}

templates/kitchen/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete dish {{dish.name}}</h1>

  <p>Are you sure you want to delete {{ dish.name }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-outline-secondary">
    <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-outline-secondary">No</a>
  </form>

{% endblock %}

templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ dish.name }} ({{ dish.dish_type.name }})
  {% if user not in dish.cooks.all  %}
    <a href="{% url 'kitchen:cook-assign-to-dish' pk=dish.id %}" class="btn btn-outline-primary link-to-page">
      Assign me to this dish
      </a>

      {% else %}
     <a href="{% url 'kitchen:cook-delete-from-dish' pk=dish.id %}" class="btn btn-outline-danger">
      Delete me from this dish
      </a>
  {% endif %}
  </h1>

  <div>
  {% if dish.cooks.all %}
    <h2>Cooks:</h2>
    {% for cook in dish.cooks.all %}
      <ul>
      <li class="list_item">
        <div class="item_content">
          <p>
            <strong>First name:</strong> {{ cook.first_name }}<br>
            <strong>Last name:</strong> {{ cook.last_name }}<br>
            <strong>Username:</strong> {{ cook.username }}<br>
            <strong>Years of experience:</strong> {{ cook.years_of_experience }}<br>
          </p>
        </div>
      </li>
      </ul>
    {% endfor %}
  {% else %}
    <p>This dish does not have any cooks</p>
  {% endif %}
  </div>
  <a class="btn btn-outline-secondary" href="{% url 'kitchen:dish-update' pk=dish.pk %}">Update</a>
  <a class="btn btn-outline-danger" href="{% url 'kitchen:dish-delete' pk=dish.pk %}">Delete</a>
{% endblock %}

templates/kitchen/dish_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} dish </h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-outline-secondary">

  </form>
{% endblock %}

templates/kitchen/dish_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Dishes <a href="{% url 'kitchen:dish-create' %}" class="btn btn-outline-secondary" >Create</a>
  </h1>
  <br>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-outline-secondary" value="🔎">
  </form>
  <br>
  <table class="table table table-dark">
    <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">Dish type</th>
    </tr>
    </thead>
    <tbody>
    {% if dish_list %}
      {% for dish in dish_list %}
        <tr>
          <td><a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.id }}</a></td>
          <td>{{ dish.name }}</td>
          <td>{{ dish.price }}</td>
          <td>{{ dish.dish_type.name }}</td>
        </tr>
      {% endfor %}
    {% else %}
      <th>There are no dishes</th>
    {% endif %}
    </tbody>
  </table>

{% endblock %}

templates/kitchen/dishe_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete dish {{dish.name}}</h1>

  <p>Are you sure you want to delete {{ dish.name }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-success">No</a>
  </form>

{% endblock %}

templates/kitchen/dishes_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete dishes type {{dishtype.name}}</h1>

  <p>Are you sure you want to delete {{ dishtype.name }}?</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-outline-danger">
    <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-outline-secondary">No</a>
  </form>

{% endblock %}

templates/kitchen/dishes_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create"}} dishes type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
     <input type="submit" value="Submit" class="btn btn-outline-secondary">

  </form>
{% endblock %}

templates/kitchen/dishes_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Types of dishes
  <a href="{% url 'kitchen:dish-type-create' %}" class="btn btn-outline-secondary"> Create </a>
  </h1>
  <br>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-outline-secondary" value="🔎">
  </form>
  <br>
  {% if dishes_type_list %}
      <table class="table table table-dark">
      <thead>
        <tr>
          <th scope="col">Id</th>
          <th scope="col">Name</th>
          <th scope="col">Update</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
          <tbody>
          {% for types in dishes_type_list %}
            <thead>
            <tr>

            <td>{{ types.id }}</td>
            <td>{{ types.name }}</td>
            <td>
              <a href="{% url 'kitchen:dish-type-update' pk=types.id %}">Update</a>
              </a>
            </td>
            <td>
              <a href="{% url 'kitchen:dish-type-delete' pk=types.id %}">Delete</a>
            </td>

      </tr>
            </thead>
          </tbody>
        {% endfor %}
      </table>
  {% else %}
    <p>There are no dish types</p>
  {% endif %}
{% endblock %}

templates/kitchen/index.html
{% extends "base.html" %}

{% block content %}
  <div style="text-shadow: 0px 0px 5px black, 0 2px 2px black,
				-2px 0 2px black,
				0 -2px 2px black;">
    <h1>Restaurant Kitchen Service</h1>
    <h5>Welcome to the greatest Kitchen Service ever!</h5>
    <h2>Kitchen service content:</h2>
    <ul>
        <li>Number of dishes: {{ num_dishes }}</li>
        <li>Number of cooks: {{ num_cooks }}</li>
        <li>Number of dishes type: {{ num_dish_types }}</li>
    </ul>
  <p>You have visited this page: {{ num_visits }} time{{ num_visits|pluralize }}.</p>
  </div>
{% endblock %}